import { jwtDecode } from "jwt-decode"
import { ClineEnv } from "@/config"
import { Controller } from "@/core/controller"
import { Logger } from "@/shared/services/Logger"
import { type ClineAccountUserInfo, type ClineAuthInfo } from "../AuthService"

/** Audiences issued by IC-AI / Vector for VS Code extension tokens */
const EXTENSION_JWT_AUDIENCES = new Set(["vector-vscode", "cline-vscode"])

interface ICAIJwtPayload {
	sub: string
	email: string
	name: string
	image?: string | null
	iat: number
	exp: number
	iss: string
	/** Single audience or list (JWT RFC allows both) */
	aud?: string | string[]
}

function jwtAudienceIsAllowed(aud: string | string[] | undefined): boolean {
	if (aud == null) {
		return false
	}
	const list = Array.isArray(aud) ? aud : [aud]
	return list.some((a) => EXTENSION_JWT_AUDIENCES.has(a))
}

export class ClineAuthProvider {
	readonly name = "icai"
	private _pendingState: string | null = null

	/**
	 * Parses a JWT payload without cryptographic verification (signature check
	 * happens server-side). Safe for extracting claims on the client side.
	 */
	parseJwt(token: string): ICAIJwtPayload | null {
		try {
			const cleaned = token.trim()
			const parts = cleaned.split(".")
			if (parts.length !== 3) {
				Logger.error(
					`[parseJwt] Invalid JWT structure: expected 3 parts, got ${parts.length}. Token length: ${cleaned.length}`,
				)
				return null
			}
			// Use jwt-decode so base64url (- _) and padding are handled correctly (Buffer "base64" alone is not JWT-safe).
			return jwtDecode<ICAIJwtPayload>(cleaned)
		} catch (error) {
			Logger.error("[parseJwt] Failed to parse JWT:", error)
			return null
		}
	}

	/**
	 * Returns seconds until the JWT expires. Negative means already expired.
	 */
	timeUntilExpiry(jwt: string): number {
		const payload = this.parseJwt(jwt)
		if (!payload?.exp) {
			return 0
		}
		return payload.exp - Date.now() / 1000
	}

	/**
	 * Checks whether the token is expired or about to expire (within 5 min).
	 */
	async shouldRefreshIdToken(_token: string, expiresAt?: number): Promise<boolean> {
		const expiration = expiresAt || 0
		const currentTime = Date.now() / 1000
		const threshold = currentTime + 5 * 60
		return expiration < threshold
	}

	/**
	 * Builds the IC-AI login URL that will be opened in the browser.
	 * The IC-AI sign-in page accepts `state` and `redirectUri` query params
	 * and uses them to redirect back to VSCode after authentication.
	 */
	async getAuthRequest(callbackUrl: string): Promise<string> {
		const state = this.generateState()
		this._pendingState = state
		const appBaseUrl = ClineEnv.config().appBaseUrl
		const loginUrl = new URL("/authorize-extension", appBaseUrl)
		loginUrl.searchParams.set("state", state)
		loginUrl.searchParams.set("redirectUri", callbackUrl)
		return loginUrl.toString()
	}

	/**
	 * Handles the auth callback from IC-AI. The token is a JWT that was already
	 * generated by IC-AI's /api/extension/token endpoint and passed via the
	 * vscode:// URI callback. No code exchange needed.
	 */
	async signIn(controller: Controller, token: string, _provider: string): Promise<ClineAuthInfo | null> {
		try {
			Logger.info(`[signIn] Received token (length=${token.length}, starts=${token.substring(0, 20)}...)`)
			const payload = this.parseJwt(token)
			if (!payload) {
				throw new Error(`Invalid JWT token received from IC-AI (length=${token.length})`)
			}
			Logger.info(`[signIn] JWT parsed: sub=${payload.sub}, aud=${payload.aud}, exp=${payload.exp}`)

			if (!jwtAudienceIsAllowed(payload.aud)) {
				throw new Error(`Invalid JWT audience: ${JSON.stringify(payload.aud)}`)
			}

			if (payload.exp < Date.now() / 1000) {
				throw new Error("JWT token has expired")
			}

			const userInfo: ClineAccountUserInfo = {
				id: payload.sub,
				email: payload.email || "",
				displayName: payload.name || payload.email || "",
				image: payload.image || undefined,
				createdAt: new Date().toISOString(),
				organizations: [],
			}

			const authInfo: ClineAuthInfo = {
				idToken: token,
				expiresAt: payload.exp,
				userInfo,
				provider: this.name,
				startedAt: Date.now(),
			}

			controller.stateManager.setSecret("cline:clineAccountId", JSON.stringify(authInfo))

			return authInfo
		} catch (error) {
			Logger.error("Error handling IC-AI auth callback:", error)
			throw error
		}
	}

	/**
	 * Retrieves stored auth info from secrets. If the JWT has expired,
	 * clears the session and returns null (user must re-authenticate).
	 */
	async retrieveClineAuthInfo(controller: Controller): Promise<ClineAuthInfo | null> {
		try {
			const storedDataString = controller.stateManager.getSecretKey("cline:clineAccountId")

			if (!storedDataString) {
				Logger.debug("No stored authentication data found")
				return null
			}

			let storedData: ClineAuthInfo
			try {
				storedData = JSON.parse(storedDataString)
			} catch {
				Logger.error("Failed to parse stored auth data")
				controller.stateManager.setSecret("cline:clineAccountId", undefined)
				return null
			}

			if (!storedData.idToken) {
				controller.stateManager.setSecret("cline:clineAccountId", undefined)
				return null
			}

			// Check if the long-lived JWT has expired
			const expiresAt = storedData.expiresAt || 0
			if (expiresAt < Date.now() / 1000) {
				Logger.info("IC-AI JWT token has expired, user needs to re-authenticate")
				controller.stateManager.setSecret("cline:clineAccountId", undefined)
				return null
			}

			return storedData
		} catch (error) {
			Logger.error("Error retrieving stored auth info:", error)
			return null
		}
	}

	/**
	 * Validates and consumes the pending state from an auth request.
	 * Returns true if the state matches the most recent request.
	 */
	validateAndConsumeState(state: string | null): boolean {
		if (!this._pendingState || !state) {
			return !this._pendingState && !state
		}
		const valid = this._pendingState === state
		if (valid) {
			this._pendingState = null
		}
		return valid
	}

	clearPendingState(): void {
		this._pendingState = null
	}

	private generateState(): string {
		const array = new Uint8Array(32)
		require("crypto").randomFillSync(array)
		return Array.from(array, (b) => b.toString(16).padStart(2, "0")).join("")
	}
}
